# docker-compose.yaml
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
